### PR TITLE
Remove no longer existing jumpTo function.

### LINKED ISSUE #426: Exception Unknown function: coc#util#jumpTo
**Describe the bug**

When trying to execute `CocCommand metals.tvp` I'm getting 

```
[coc.nvim]: UnhandledRejection: request error nvim_call_function - Vim:E117: Unknown
 function: coc#util#jumpTo
Error
    at ON.request (/Users/oliver/.tilde/dotfiles/.config/nvim/plugged/coc.nvim/build
/index.js:30:34613)
    at ON.call (/Users/oliver/.tilde/dotfiles/.config/nvim/plugged/coc.nvim/build/in
dex.js:33:3671)
    at o.<anonymous> (/Users/oliver/.tilde/dotfiles/.config/nvim/plugged/coc-metals/
lib/index.js:14:2546)
    at Generator.next (<anonymous>)
    at s (/Users/oliver/.tilde/dotfiles/.config/nvim/plugged/coc-metals/lib/index.js
:14:123)
```

**To Reproduce** Steps to reproduce the behavior:

1. Have Scala project
have:
vim version: NVIM v0.6.0-dev+nightly-380-gdf33f30e8
node version: v12.20.2
coc.nvim version: 0.0.80-3086844413
coc.nvim directory: /Users/oliver/.tilde/dotfiles/.config/nvim/plugged/coc.nvim
term: tmux
platform: darwin

Install coc-metals via

`Plug 'scalameta/coc-metals', {'do': 'yarn install --frozen-lockfile'} `

Use

`nnoremap <silent> <space>t :<C-u>CocCommand metals.tvp<CR>` on project

Fail.

**Expected behavior**

Show tree
**Screenshots**

n/A

**Installation:**

vim version: NVIM v0.6.0-dev+nightly-380-gdf33f30e8
node version: v12.20.2
coc.nvim version: 0.0.80-3086844413
coc.nvim directory: /Users/oliver/.tilde/dotfiles/.config/nvim/plugged/coc.nvim
term: tmux
platform: darwin

main branch of coc-metals since I already needed to pull in for https://github.com/scalameta/coc-metals/issues/421

**Additional context**

**Search terms**

### PR DESCRIPTION
**Pull request by ckipp01**
This was removed and replaced with the `coc#cursor#move_to` in https://github.com/neoclide/coc.nvim/commit/00ed6677383e56d79cb2812bfe954f424bb15ded

Close #426

### CODE REVIEW

File: src/commands.ts [hunk 1]
```diff
@@ -26,4 +26,8 @@ export namespace Commands {
    * Shows Coc Info and logs
    */
   export const OPEN_LOGS = "CocCommand workspace.showOutput";
+  /**
+   * Move the cursor to the specified position
+   */
+  export const MOVE_TO = "coc#cursor#move_to";
```
Comment (jsatk) [inline src/commands.ts:32]: Good move specifying it once here in case we have to do this sort of update again.

**Review by jsatk — APPROVED** [review]
Thanks for this!
